# Generated by Django 5.1 on 2026-02-26 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'CompanyCodes',
                'db_table': 'Aspl_CompanyCode',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'CostCenters',
                'db_table': 'Aspl_CostCenter',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'Aspl_Department',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'EmployeeRoles',
                'db_table': 'Aspl_EmployeeRole',
            },
        ),
        migrations.CreateModel(
            name='OfficeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aspl_Branches',
                'db_table': 'Aspl_Branch',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('empID', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('otp', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('dol', models.DateField(blank=True, null=True)),
                ('companyCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_companycode', to='account.companycode')),
                ('costcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employe_costcenter', to='account.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_department', to='account.department')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_role', to='account.employeerole')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_working_brach', to='account.officebranch')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_department', to='account.organization')),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'db_table': 'Aspl_Employee',
                'ordering': ['empID'],
            },
        ),
    ]
