# Generated by Django 5.1 on 2026-02-26 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('projectdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('bill', models.BooleanField(blank=True, null=True)),
                ('location', models.CharField(choices=[('WFH', 'WFH'), ('OnSite', 'OnSite'), ('Office', 'Office')], max_length=50)),
                ('year_week', models.CharField(max_length=30, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_employee', to=settings.AUTH_USER_MODEL)),
                ('employee_costcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_emp_costcenter', to='account.costcenter')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_project', to='projectdata.project')),
                ('project_subcode_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_project_subcode_activity', to='projectdata.projectsubcodeactivity')),
                ('projectsubcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_projectsubcode', to='projectdata.projectsubcode')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_status', to='timesheet.status')),
            ],
            options={
                'db_table': 'Aspl_Timesheet',
                'ordering': ['-date'],
            },
        ),
    ]
