# Generated by Django 5.1 on 2026-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
