# Generated by Django 5.1 on 2026-02-26 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('track_time', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tracker', to='account.department')),
            ],
            options={
                'verbose_name_plural': 'Department Trackers',
                'db_table': 'Department_tracker',
            },
        ),
        migrations.CreateModel(
            name='LeaveAppication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_half', models.CharField(choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=20)),
                ('end_date', models.DateField()),
                ('end_half', models.CharField(choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('total_days', models.FloatField(blank=True, null=True)),
                ('leave_type', models.CharField(choices=[('paid_leave', 'paid_leave'), ('loss_of_paid_leave', 'loss_of_paid_leave')], max_length=30)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approver', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_appli_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leave Appications',
                'db_table': 'Leave_Appication',
            },
        ),
    ]
